languageCode = "es"
languageName = "Español"
weight = 1
title = "Shunya"

[params]
  displayName = "Español"
  isoCode = "es-ES"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/shunya_logo_no_bg.png"
  secondaryLogo = "img/shunya_logo_no_bg_black.png"
  description = "Shunya's blog"

[params.author]
  name = "Victor Luque"
  email = "luque.viictor@gmail.com"
  image = "img/myself.jpg"
  headline = "Embedded Software Engineer @ INBRAIN"
  bio = "Embedded Software Engineer @ INBRAIN"
  links = [
    { x-twitter = "https://x.com/itsshunya" },
    { github = "https://github.com/itsshunya" },
    { linkedin = "https://linkedin.com/in/victorluquemartinez" },
    { email = "mailto:luque.viictor@gmail.com" },
    { instagram = "https://instagram.com/shunyavic" },
    { dev = "https://dev.to/itsshunya" },
  ]